using LinearAlgebra
using TOML

# This file tests the irreducible representations of the symmetry groups of finite
# lattices (src/symmetry/pointgroups.jl, kpoints.jl, irreps.jl) and their TOML output.
#
# Besides hand-derived expectations for the momenta, every cluster is checked with
# group-theoretical identities that do not rely on the implementation:
#  - the characters of each sector are multiplicative on its group (as checked by XDiag),
#  - the dimension of each sector in the spin-1/2 Hilbert space, from the character formula
#    dim = (1/|S|) Σ_s conj(χ(s)) 2^(number of cycles of s), is a non-negative integer,
#  - completeness: Σ_stars |star| Σ_sectors dim = 2^N, and binomial(N, nup) for every S^z,
#  - the names of the irreps are covariant: computed at any momentum of a star, they agree with
#    those at the representative carried over by a symmetry of the cluster,
#  - labels and dimensions do not depend on the description of the cluster (basis of the lattice,
#    boundary vectors, rotations, shifts, order of the sites).
# The characters are also compared with the legacy maple-leaf files, which were generated by
# an independent code, and two sector dimensions with values from the literature.


# number of cycles of a permutation
function ncycles(p::Vector{Int})
    seen = falses(length(p))
    n = 0
    for i in eachindex(p)
        seen[i] && continue
        n += 1
        j = i
        while !seen[j]
            seen[j] = true
            j = p[j]
        end
    end
    return n
end

# dimension of a sector in the spin-1/2 Hilbert space (floating-point reference for `sector_dimension`)
function reference_dimension(cs::ClusterSymmetries, irrep::Irrep)
    P = cs.permutations
    d = sum(conj(χ) * 2.0^ncycles(P[i]) for (i, χ) in zip(irrep.allowed_symmetries, irrep.characters))
    return d / length(irrep.allowed_symmetries)
end

function characters_multiplicative(cs::ClusterSymmetries, irrep::Irrep)
    P = cs.permutations
    index = Dict(p => i for (i, p) in enumerate(P))
    χ = Dict(zip(irrep.allowed_symmetries, irrep.characters))
    for i in irrep.allowed_symmetries, j in irrep.allowed_symmetries
        ij = index[P[i][P[j]]]   # first j, then i
        (haskey(χ, ij) && isapprox(χ[ij], χ[i] * χ[j]; atol=1e-10)) || return false
    end
    return true
end

# names of the irreps of the little co-group of the momentum k: name => set of exponent tables
# (W => exponent mod 12); the partners a/b of a two-dimensional irrep are kept as a pair under
# the name of the irrep, since which one is a depends on the symmetry relating two momenta
function named_sectors(cs::ClusterSymmetries, k::ClusterMomentum)
    lattice = cs.spacegroup.flattice.lattice
    holo = Latlib.dim(lattice) == 2 ? Latlib._holohedry(lattice) : Latlib._holohedry3d(lattice)
    _, Ws, sectors, _ = Latlib._pointgroup_sectors(k.littlegroup, lattice, Latlib._naming_context(lattice, holo, k))
    result = Dict{String, Set{Dict{Matrix{Int}, Int}}}()
    for s in sectors
        table = Dict(Ws[s.elements[j]] => s.exponents[j] for j in eachindex(s.elements))
        push!(get!(result, s.dimension == 2 ? s.parent : s.name, Set{Dict{Matrix{Int}, Int}}()), table)
    end
    return result
end

# whether the names at every momentum of a star agree with those at the representative, carried
# over by a rotation W of the cluster (k -> W^{-T} k in the reciprocal basis, X -> W X W^{-1})
function names_covariant(cs::ClusterSymmetries)
    ks = momenta(cs)
    for k in ks
        k.representative || continue
        reference = named_sectors(cs, k)
        for q in ks
            (q.star == k.star && q !== k) || continue
            W = first(W for W in cs.pointgroup if all(iszero, mod.(round.(Int, inv(W))' * k.coords - q.coords, 1)))
            carried = Dict(name => Set(Dict(round.(Int, W * X / W) => a for (X, a) in table) for table in tables)
                           for (name, tables) in reference)
            carried == named_sectors(cs, q) || return false
        end
    end
    return true
end

# labels of the written sectors with their dimensions for every number of up spins
function fingerprint(cs::ClusterSymmetries)
    N = length(cs.permutations[1])
    return sort([(irrep.label, [sector_dimension(cs, irrep; nup) for nup in 0:N])
                 for (irrep, status) in Latlib._sectors(cs) if status == :ok])
end

site_origin(lattice) = LatticeVector(lattice, [0.0, 0.0])
site_origin3(lattice) = LatticeVector(lattice, [0.0, 0.0, 0.0])
const rectangular = Lattice([1.0 0.0; 0.0 1.5])
const trellis_origin = LatticeVector(trellis, spacegroup(trellis).origin)

# (lattice, boundary, origin, representatives "label.littlegroup" (sorted), number of sectors, number of vanishing sectors)
const IRREP_CASES = [
    (maple_leaf,  [1 1; 1 -2],  nothing,                 ["Gamma.C6", "K.C3"], 9, 0),
    (maple_leaf,  [1 0; 0 2],   nothing,                 ["Gamma.C2", "M.C2"], 4, 0),
    (triangular,  [3 0; 0 3],   nothing,                 ["Gamma.C6v", "K.C3v", "Sigma.Cs"], 14, 0),
    (triangular,  [2 0; 0 1],   nothing,                 ["Gamma.C2v", "M.C2v"], 2, 6),          # two sites
    (triangular,  [3 1; -1 4],  nothing,                 ["GP0.C1", "GP1.C1", "Gamma.C6"], 8, 0),  # 13 sites, chiral
    (honeycomb,   [3 0; 0 3],   nothing,                 ["Gamma.C6v", "K.C3v", "Sigma.Cs"], 14, 0),
    (honeycomb,   [2 -2; 1 1],  nothing,                 ["Gamma.C2v", "Lambda.Cs", "M.C2v"], 10, 0),
    (kagome,      [2 0; 0 2],   nothing,                 ["Gamma.C6v", "M.C2v"], 12, 0),
    (square,      [4 0; 0 4],   site_origin(square),     ["Delta.Cs", "Gamma.C4v", "M.C4v", "Sigma.Cs", "X.C2v", "Y.Cs"], 22, 0),
    (square,      [4 0; 0 2],   site_origin(square),     ["Delta.Cs", "Gamma.C2v", "M.C2v", "X0.C2v", "X1.C2v", "Y.Cs"], 10, 10),  # mirror y -> -y trivial
    (square,      [3 1; -1 3],  site_origin(square),     ["GP0.C1", "GP1.C1", "Gamma.C4", "M.C4"], 10, 0),
    (lieb,        [2 0; 0 2],   site_origin(lieb),       ["Gamma.C4v", "M.C4v", "X.C2v"], 16, 0),
    (trellis,     [4 0; -2 4],  trellis_origin,          ["C.Cs", "Delta.Cs", "GP0.C1", "Gamma.C2v", "S.C2", "Sigma0.Cs", "Sigma1.Cs", "Y.C2v"], 19, 0),
    (trellis,     [3 0; 1 2],   trellis_origin,          ["GP0.C1", "GP1.C1", "Gamma.C2", "Y.C2"], 6, 0),
    (rectangular, [4 0; 0 4],   site_origin(rectangular), ["C.Cs", "D.Cs", "Delta.Cs", "GP0.C1", "Gamma.C2v", "S.C2v", "Sigma.Cs", "X.C2v", "Y.C2v"], 25, 0),
    (rectangular, [2 0; 0 3],   site_origin(rectangular), ["D.Cs", "Delta.Cs", "Gamma.C2v", "X.C2v"], 6, 6),  # mirror x -> -x trivial
]

const LEGACY_FILES = ["maple.leaf.JhexagonJtriangleJdimer.12.v1.2sl.toml",
                      "maple.leaf.JhexagonJtriangleJdimer.18.v1.2sl.toml",
                      "maple.leaf.JhexagonJtriangleJdimer.24.v2.2sl.toml",
                      "maple.leaf.JhexagonJtriangleJdimer.36.v3.2sl.toml",
                      "maple.leaf.JhexagonJtriangleJdimer.54.v1.2sl.toml"]


@testset "Irreducible representations" begin

    @testset "point groups" begin
        # irrep names of the little co-groups at Gamma of lattices with full symmetry
        names(cs) = sort([irrep.name for irrep in irreps(cs) if irrep.kpoint == "Gamma"])
        @test names(symmetries(FiniteLattice(triangular, [3 0; 0 3], true))) == ["A1", "A2", "B1", "B2", "E1a", "E1b", "E2a", "E2b"]
        @test names(symmetries(FiniteLattice(maple_leaf, [1 1; 1 -2], true))) == ["A", "B", "E1a", "E1b", "E2a", "E2b"]
        @test names(symmetries(FiniteLattice(square, [4 0; 0 4], true); origin=site_origin(square))) == ["A1", "A2", "B1", "B2", "Ea", "Eb"]
        @test names(symmetries(FiniteLattice(square, [3 1; -1 3], true); origin=site_origin(square))) == ["A", "B", "Ea", "Eb"]
        @test names(symmetries(FiniteLattice(rectangular, [4 0; 0 4], true); origin=site_origin(rectangular))) == ["A1", "A2", "B1", "B2"]
        @test sort(unique(irrep.name for irrep in irreps(symmetries(FiniteLattice(triangular, [3 0; 0 3], true))) if irrep.kpoint == "K")) == ["A1", "A2", "Ea", "Eb"]
        @test sort(unique(irrep.name for irrep in irreps(symmetries(FiniteLattice(triangular, [3 0; 0 3], true))) if irrep.kpoint == "Sigma")) == ["Ap", "App"]

        # Bilbao conventions for B1/B2 at Gamma of C6v: B1 is even under mirrors whose normal is a lattice vector
        cs = symmetries(FiniteLattice(triangular, [3 0; 0 3], true))
        B1 = only(irrep for irrep in irreps(cs) if irrep.label == "Gamma.C6v.B1")
        ops = operations(cs.spacegroup)
        for (j, opindex) in enumerate(cs.operations)
            W = ops[opindex].W
            R = triangular.A' * W / triangular.A'
            (det(R) < 0 && iszero(cs.translations[j])) || continue
            normal = nullspace(R + I)[:, 1]
            normal_is_lattice_vector = any(v -> abs(normal[1] * v[2] - normal[2] * v[1]) < 1e-8,
                                           [triangular.A' * [1, 0], triangular.A' * [0, 1], triangular.A' * [1, -1]])
            χ = B1.characters[findfirst(==(cs.permutation_index[j]), B1.allowed_symmetries)]
            @test χ ≈ (normal_is_lattice_vector ? 1 : -1)
        end

        # two-dimensional irreps of C6v: partners a/b on C6 are complex conjugate at Gamma
        E1a = only(irrep for irrep in irreps(cs) if irrep.label == "Gamma.C6v.E1a")
        E1b = only(irrep for irrep in irreps(cs) if irrep.label == "Gamma.C6v.E1b")
        @test E1a.parent == "E1" && E1a.dimension == 2
        @test E1a.allowed_symmetries == E1b.allowed_symmetries
        @test E1a.characters ≈ conj.(E1b.characters)
        @test length(E1a.allowed_symmetries) == 6 * 9   # C6 times translations
        @test reference_dimension(cs, E1a) ≈ reference_dimension(cs, E1b)
        # complex one-dimensional irreps of C6 are not split
        cs6 = symmetries(FiniteLattice(maple_leaf, [1 1; 1 -2], true))
        @test all(irrep -> irrep.dimension == 1 && irrep.parent == irrep.name, irreps(cs6))
    end

    @testset "momenta and sectors" begin
        for (lattice, boundary, origin, representatives, nsectors, nvanishing) in IRREP_CASES
            fl = FiniteLattice(lattice, boundary, true)
            cs = symmetries(fl; origin=origin)
            ks = momenta(cs)
            N = length(atoms(fl))

            # momenta: one per Bravais cell, stars partition them, one representative per star
            @test length(ks) == length(bravais_cells(fl))
            @test count(k -> k.representative, ks) == length(unique(k.star for k in ks))
            @test sort(["$(k.label).$(k.littlegroup_name)" for k in ks if k.representative]) == representatives
            @test all(k -> k.label == first(q.label for q in ks if q.star == k.star), ks)

            # sectors
            irs = irreps(cs)
            @test length(irs) == nsectors
            @test length(Latlib._sectors(cs)) == nsectors + nvanishing
            @test allunique(irrep.label for irrep in irs)
            @test all(irrep -> irrep.allowed_symmetries[1] == 1 && irrep.characters[1] ≈ 1, irs)
            @test all(irrep -> characters_multiplicative(cs, irrep), irs)
            @test allunique(cs.permutations)
            @test cs.permutations[1] == collect(1:N)

            # dimensions are non-negative integers and add up to the full Hilbert space
            starsize = Dict(k.label => count(q -> q.star == k.star, ks) for k in ks if k.representative)
            dims = [reference_dimension(cs, irrep) for irrep in irs]
            @test all(d -> abs(imag(d)) < 1e-6 && abs(real(d) - round(real(d))) < 1e-6 && real(d) > -1e-6, dims)
            @test round(Int, sum(starsize[irrep.kpoint] * real(d) for (irrep, d) in zip(irs, dims))) == 2^N
        end
    end

    @testset "symmetry center" begin
        fl = FiniteLattice(square, [4 0; 0 4], true)
        # ambiguous for the square lattice: site or plaquette center
        @test_throws ArgumentError symmetries(fl)
        err = try symmetries(fl) catch e e end
        @test occursin("ambiguous", err.msg) && occursin("(1/2, 1/2)", err.msg)
        # not a point with the full point-group symmetry
        @test_throws ArgumentError symmetries(fl; origin=LatticeVector(square, [0.5, 0.0]))
        # unique for hexagonal lattices: hexagon centers of honeycomb and kagome
        @test symmetries(FiniteLattice(honeycomb, [3 0; 0 3], true)).origin ≈ [2/3, 2/3]
        @test symmetries(FiniteLattice(kagome, [2 0; 0 2], true)).origin ≈ [1/2, 1/2]
        # origin as EuclideanVector
        @test symmetries(fl; origin=EuclideanVector([0.5, 0.5])).origin ≈ [0.5, 0.5]

        # the two centers give the same sectors at M, with different labels
        cs1 = symmetries(fl; origin=LatticeVector(square, [0.0, 0.0]))
        cs2 = symmetries(fl; origin=LatticeVector(square, [0.5, 0.5]))
        @test cs1.permutations == cs2.permutations
        sectors_at_M(cs) = Dict(irrep.name => Dict(zip(irrep.allowed_symmetries, irrep.characters)) for irrep in irreps(cs) if irrep.kpoint == "M")
        M1, M2 = sectors_at_M(cs1), sectors_at_M(cs2)
        @test Set(values(M1)) == Set(values(M2))
        @test any(name -> M1[name] != M2[name], keys(M1))
        # but not at Gamma
        sectors_at_Γ(cs) = Dict(irrep.name => irrep.characters for irrep in irreps(cs) if irrep.kpoint == "Gamma")
        @test sectors_at_Γ(cs1) == sectors_at_Γ(cs2)
    end

    @testset "unsupported cases" begin
        @test_throws ArgumentError symmetries(FiniteLattice(shastry_sutherland_non_symmorphic, [2 0; 0 2], true))   # p4gm
        @test_throws ArgumentError symmetries(FiniteLattice(diamond, [-1 1 1; 1 -1 1; 1 1 -1], true))            # Fd-3m
        @test_throws ArgumentError symmetries(FiniteLattice(triangular, [3 0; 0 3], [true, false]))              # open
        # non-primitive unit cell: only translations by lattice vectors are used
        fl = FiniteLattice(shastry_sutherland, [2 0; 0 2], true)
        cs = @test_logs (:warn, r"not primitive") symmetries(fl; origin=site_origin(shastry_sutherland))
        @test length(cs.operations) == 8 * 4
        @test length(cs.operations) < length(cs.spacegroup)
    end

    @testset "legacy maple-leaf files" begin
        parse_vector(text, name) = parse.(Float64, split(match(Regex(name * raw"=\(([^)]*)\)"), text)[1], ","))
        # Bilbao labels replace the labels of the legacy code for lines and generic momenta
        legacy_base(label) = (m = match(r"^([A-Za-z]*)\d*$", label); base = m[1];
                              base == "" ? "GP" : base == "X" ? "Lambda" : base == "Y" ? "Sigma" : base == "Z" ? "T" : base)
        for file in LEGACY_FILES
            @testset "$file" begin
                path = joinpath(@__DIR__, "data", "legacy", file)
                text = read(path, String)
                data = TOML.parsefile(path)
                t = hcat(parse_vector(text, "t1"), parse_vector(text, "t2"))
                fl = FiniteLattice(maple_leaf, round.(Int, (maple_leaf.A' \ t)'), true)
                cs = symmetries(fl)
                ours = irreps(cs)

                # map legacy sites onto ours by position modulo the torus
                T = Matrix{Float64}(fl.boundary')
                X = [maple_leaf.A' \ x.coords for x in atoms(fl)]
                same(x, y) = (u = T \ (x - y); norm(u - round.(u)) < 1e-6)
                σ = [findfirst(y -> same(maple_leaf.A' \ Float64.(c), y), X) for c in data["Coordinates"]]
                legacy_perm(q) = (p = zeros(Int, length(q)); for i in eachindex(q); p[σ[i]] = σ[q[i] + 1]; end; p)

                legacy_labels = String[]
                for (k, v) in data, (gname, v2) in (v isa Dict ? v : Dict()), (name, rep) in v2
                    push!(legacy_labels, k)
                    # duplicate representative of the legacy code (see roadmap §1.4): K1 ~ K0 in 36.v3
                    (occursin("36.v3", file) && k == "K1") && continue
                    κ = maple_leaf.A * Float64.(rep["momentum"]) / 2π
                    match_ = [ir for ir in ours if ir.name == name && ir.littlegroup == gname &&
                              (d = maple_leaf.A * ir.momentum / 2π - κ; norm(d - round.(d)) < 1e-6)]
                    @test length(match_) == 1
                    isempty(match_) && continue
                    ir = match_[1]
                    @test legacy_base(k) == match(r"^([A-Za-z]*)\d*$", ir.kpoint)[1]
                    ourχ = Dict(cs.permutations[i] => χ for (i, χ) in zip(ir.allowed_symmetries, ir.characters))
                    legχ = Dict(legacy_perm(data["Symmetries"][s + 1]) => complex(c...) for (s, c) in zip(rep["allowed_symmetries"], rep["characters"]))
                    @test keys(ourχ) == keys(legχ)
                    @test all(p -> isapprox(ourχ[p], legχ[p]; atol=1e-12), collect(keys(legχ)))
                end
                # every sector of ours is in the legacy file (up to the merged duplicate)
                @test length(ours) == count(l -> !(occursin("36.v3", file) && l == "K1"), legacy_labels)
            end
        end
    end

    @testset "TOML output" begin
        # maple leaf, 18 sites: same sections as the legacy file
        fl = FiniteLattice(maple_leaf, [1 1; 1 -2], true)
        H = neighbor_interaction("SdotS", "J", fl)
        cs = symmetries(fl)
        s = write_toml(fl, H, ""; zero_based=true, return_string=true, symmetries=true)
        @test s == write_toml(fl, H, ""; zero_based=true, return_string=true, symmetries=cs)
        data = TOML.parse(s)
        @test data["Symmetries"] == [p .- 1 for p in cs.permutations]
        legacy = TOML.parsefile(joinpath(@__DIR__, "data", "legacy", LEGACY_FILES[2]))
        labels(d) = Set("$k.$g.$i" for (k, v) in d if v isa Dict for (g, v2) in v for (i, _) in v2)
        @test labels(data) == labels(legacy)
        for irrep in irreps(cs)
            k, g, i = split(irrep.label, ".")
            section = data[k][g][i]
            @test section["allowed_symmetries"] == irrep.allowed_symmetries .- 1
            @test [complex(c...) for c in section["characters"]] ≈ irrep.characters
            @test section["momentum"] ≈ irrep.momentum
        end
        @test occursin("# Symmetry center: (3/7, 5/7)", s)
        @test occursin("#   K        C3    (1.5832138823, 0.0000000000) *", s)
        @test !occursin("PLACEHOLDER", s)

        # two-dimensional irreps are marked
        fl3 = FiniteLattice(triangular, [3 0; 0 3], true)
        s3 = write_toml(fl3, neighbor_interaction("SdotS", "J", fl3), ""; zero_based=true, return_string=true, symmetries=true)
        @test occursin("# Gamma.C6v.E1 is two-dimensional", s3)
        @test haskey(TOML.parse(s3)["Gamma"]["C6v"], "E1a")

        # thin cluster: omitted operations and vanishing irreps are reported
        fl2 = FiniteLattice(square, [4 0; 0 2], true)
        H2 = neighbor_interaction("SdotS", "J", fl2)
        @test_throws ArgumentError write_toml(fl2, H2, ""; zero_based=true, return_string=true, symmetries=true)   # ambiguous center
        cs2 = symmetries(fl2; origin=site_origin(square))
        s2 = write_toml(fl2, H2, ""; zero_based=true, return_string=true, symmetries=cs2)
        data2 = TOML.parse(s2)
        @test length(data2["Symmetries"]) == 16
        @test occursin("PLACEHOLDER (TOML format to be decided): omitted symmetry operations", s2)
        @test occursin("PLACEHOLDER (TOML format to be decided): omitted irreducible representations", s2)
        @test occursin("#   Gamma.C2v.B2\n", s2)
        @test !haskey(data2["Gamma"]["C2v"], "B2")
        @test haskey(data2["Gamma"]["C2v"], "A1")
    end

    @testset "write_toml for all space groups" begin
        toml(fl; kwargs...) = write_toml(fl, neighbor_interaction("SdotS", "J", fl), ""; zero_based=true, return_string=true, kwargs...)

        # symmorphic, unique symmetry center: irreps are written automatically
        fl = FiniteLattice(triangular, [3 0; 0 3], true)
        s = @test_logs toml(fl; symmetries=true)
        @test occursin("# Irreducible representations\n", s)
        @test s == toml(fl; symmetries=spacegroup(fl)) == toml(fl; symmetries=symmetries(fl))
        # ... unless irreps=false
        s_noirreps = @test_logs toml(fl; symmetries=true, irreps=false)
        @test !occursin("# Irreducible representations\n", s_noirreps)
        @test TOML.parse(s_noirreps)["Symmetries"] == TOML.parse(s)["Symmetries"]
        s_cs = toml(fl; symmetries=symmetries(fl), irreps=false)
        @test haskey(TOML.parse(s_cs), "Symmetries") && !occursin("# Irreducible representations\n", s_cs)

        # symmorphic, ambiguous symmetry center: `origin` is needed for irreps, but not without them
        fl = FiniteLattice(square, [4 0; 0 4], true)
        @test_throws ArgumentError toml(fl; symmetries=true)
        s_origin = toml(fl; symmetries=true, origin=site_origin(square))
        @test s_origin == toml(fl; symmetries=symmetries(fl; origin=site_origin(square)))
        @test occursin("[M.C4v.A1]", s_origin)
        s_noirreps = @test_logs toml(fl; symmetries=true, irreps=false)
        @test length(TOML.parse(s_noirreps)["Symmetries"]) == 128
        @test_throws ArgumentError toml(fl; symmetries=symmetries(fl; origin=site_origin(square)), origin=site_origin(square))

        # non-symmorphic: only the symmetry operations, with a warning
        for (lattice, boundary, nperms) in [(shastry_sutherland_non_symmorphic, [2 0; 0 2], 32),   # p4gm
                                            (diamond, [-1 1 1; 1 -1 1; 1 1 -1], 192),           # Fd-3m
                                            (hcp, [3 0 0; 0 3 0; 0 0 2], 432)]                   # P6_3/mmc
            fl = FiniteLattice(lattice, boundary, true)
            s = @test_logs (:warn, r"not implemented for non-symmorphic space groups") toml(fl; symmetries=true)
            data = TOML.parse(s)
            @test length(data["Symmetries"]) == nperms
            @test data["Symmetries"] == [p .- 1 for p in site_permutations(spacegroup(fl))[distinct_operations(spacegroup(fl))]]
            @test !occursin("# Irreducible representations\n", s)
            # no warning if irreps are not requested
            @test (@test_logs toml(fl; symmetries=true, irreps=false)) == s
        end

        # three-dimensional symmorphic: irreps, with a banner and a warning for skipped three-dimensional irreps
        fl = FiniteLattice(simple_cubic, [2 0 0; 0 2 0; 0 0 2], true)
        @test_throws ArgumentError toml(fl; symmetries=true)                                     # ambiguous center
        s = @test_logs (:warn, r"Three-dimensional irreducible representations are skipped") toml(fl; symmetries=true, origin=LatticeVector(simple_cubic, [0.0, 0.0, 0.0]))
        @test length(TOML.parse(s)["Symmetries"]) == 48
        @test occursin("# Irreducible representations\n", s)
        @test count("WARNING: three-dimensional irreducible representations were SKIPPED", s) == 2   # top of the file and irreps
        @test occursin("# !!!   Gamma.Oh.T1u\n", s)
        s_noirreps = @test_logs toml(fl; symmetries=true, irreps=false)
        @test !occursin("# Irreducible representations\n", s_noirreps) && !occursin("SKIPPED", s_noirreps)
    end

    @testset "three-dimensional lattices" begin
        o(lattice) = LatticeVector(lattice, [0.0, 0.0, 0.0])
        tetragonal = Lattice([1.0 0 0; 0 1 0; 0 0 1.7])
        bct = Lattice([-0.5 0.5 0.8; 0.5 -0.5 0.8; 0.5 0.5 -0.8])
        orthorhombic = Lattice([1.0 0 0; 0 1.3 0; 0 0 1.7])
        α = 1.2
        rhombohedral = Lattice([1.0 0 0; cos(α) sin(α) 0;
                                cos(α) (cos(α) - cos(α)^2) / sin(α) sqrt(1 - cos(α)^2 - ((cos(α) - cos(α)^2) / sin(α))^2)])
        monoclinic = Lattice([1.0 0 0; 0 1.4 0; 0.3 0 1.9])
        triclinic = Lattice([1.0 0 0; 0.2 1.3 0; 0.3 0.4 1.6])
        cases = [
            # (lattice, boundary, origin, representatives, sectors, skipped 3D irreps, vanishing sectors)
            (simple_cubic, [2 0 0; 0 2 0; 0 0 2], o(simple_cubic), ["Gamma.Oh", "M.D4h", "R.Oh", "X.D4h"], 12, 8, 28),
            (simple_cubic, [3 0 0; 0 3 0; 0 0 3], o(simple_cubic), ["Delta.C4v", "Gamma.Oh", "Lambda.C3v", "Sigma.C2v"], 22, 4, 0),
            (simple_cubic, [4 0 0; 0 2 0; 0 0 2], o(simple_cubic), ["Delta.C4v", "Gamma.D4h", "M0.D2h", "M1.D4h", "R.D4h", "T.C4v", "X0.D4h", "X1.D2h", "Z.C2v"], 25, 0, 55),
            (bcc, 2 * [0 1 1; 1 0 1; 1 1 0], nothing, ["Delta.C4v", "Gamma.Oh", "H.Oh", "N.D2h", "P.Td"], 34, 10, 0),
            (fcc, [-2 2 2; 2 -2 2; 2 2 -2], o(fcc), ["Delta.C4v", "Gamma.Oh", "L.D3d", "Sigma.C2v", "W.D2d", "X.D4h"], 44, 4, 0),
            (simple_hexagonal, [3 0 0; 0 3 0; 0 0 2], o(simple_hexagonal), ["A.D6h", "Gamma.D6h", "H.D3h", "K.D3h", "R.C2v", "Sigma.C2v"], 28, 0, 28),
            (tetragonal, [2 0 0; 0 2 0; 0 0 3], o(tetragonal), ["Gamma.D4h", "Lambda.C4v", "M.D4h", "V.C4v", "W.C2v", "X.D2h"], 15, 0, 33),
            (bct, [2 0 0; 0 2 0; 0 0 2], o(bct), ["Gamma.D4h", "M.D4h", "N.C2h", "X.D2h"], 18, 0, 18),
            (orthorhombic, [2 0 0; 0 2 0; 0 0 3], o(orthorhombic), ["G.C2v", "Gamma.D2h", "H.C2v", "Lambda.C2v", "Q.C2v", "S.D2h", "X.D2h", "Y.D2h"], 12, 0, 36),
            (rhombohedral, [2 0 0; 0 2 0; 0 0 2], o(rhombohedral), ["F.C2h", "Gamma.D3d", "L.C2h", "T.D3d"], 12, 0, 12),
            (monoclinic, [2 0 0; 0 2 0; 0 0 2], o(monoclinic), ["A.C2h", "B.C2h", "C.C2h", "D.C2h", "E.C2h", "Gamma.C2h", "Y.C2h", "Z.C2h"], 8, 0, 24),
            (triclinic, [2 0 0; 0 2 0; 0 0 2], o(triclinic), ["Gamma.Ci", "R.Ci", "T.Ci", "U.Ci", "V.Ci", "X.Ci", "Y.Ci", "Z.Ci"], 8, 0, 8),
        ]
        for (lattice, boundary, origin, representatives, nsectors, nskipped, nvanishing) in cases
            fl = FiniteLattice(lattice, boundary, true)
            cs = symmetries(fl; origin=origin)
            ks = momenta(cs)
            N = length(atoms(fl))
            P = cs.permutations
            @test sort(["$(k.label).$(k.littlegroup_name)" for k in ks if k.representative]) == representatives

            # labels: the little co-group in the holohedry has the order given in the table of the label
            holo = Latlib._holohedry3d(lattice)
            order = Dict(f.label => f.order for f in holo.families)
            for k in ks
                base = match(r"^(.*?)\d*$", k.label)[1]
                expected = base == "Gamma" ? length(holo.rotations) : base == "GP" ? 1 : order[base]
                @test Latlib._holohedry_littlegroup_order(lattice, holo.rotations, k.momentum) == expected
            end

            sectors = Latlib._sectors(cs)
            @test count(s -> s[2] == :ok, sectors) == nsectors
            @test count(s -> s[2] == :skipped, sectors) == nskipped
            @test count(s -> s[2] == :vanishing, sectors) == nvanishing
            irs = nskipped > 0 ? (@test_logs (:warn, r"skipped") irreps(cs)) : irreps(cs)
            @test all(irrep -> characters_multiplicative(cs, irrep), irs)

            # completeness per momentum: the subspace of momentum k (from the translations alone) is spanned
            # by the sectors and the skipped three-dimensional irreps (dimension 3 × multiplicity)
            ops = operations(cs.spacegroup)
            translations = [j for j in eachindex(cs.operations) if ops[cs.operations[j]].W == I]
            total = 0.0
            for k in ks
                k.representative || continue
                dimk = real(sum(cispi(-2 * Float64(sum(k.coords .* cs.translations[j]))) * 2.0^ncycles(P[cs.permutation_index[j]])
                                for j in translations)) / length(translations)
                dims = [reference_dimension(cs, irrep) for irrep in irs if irrep.kpoint == k.label]
                @test all(d -> abs(imag(d)) < 1e-6 && abs(real(d) - round(real(d))) < 1e-6 && real(d) > -1e-6, dims)
                rest = dimk - sum(real, dims; init=0.0)
                @test rest > -1e-6 && abs(rest / 3 - round(rest / 3)) < 1e-6
                any(s -> s[1].kpoint == k.label && s[2] == :skipped, sectors) || @test abs(rest) < 1e-6
                total += count(q -> q.star == k.star, ks) * dimk
            end
            @test round(Int, total) == 2^N
        end

        # names of the irreps (Mulliken, Bilbao conventions)
        names(cs, k) = sort(unique(irrep.littlegroup * "." * irrep.name for irrep in irreps(cs) if irrep.kpoint == k))
        cs = symmetries(FiniteLattice(bcc, 2 * [0 1 1; 1 0 1; 1 1 0], true))
        @test (@test_logs (:warn,) names(cs, "Gamma")) == ["Oh.A1g", "Oh.A1u", "Oh.A2g", "Oh.A2u", "Oh.Ega", "Oh.Egb", "Oh.Eua", "Oh.Eub"]
        @test (@test_logs (:warn,) names(cs, "P")) == ["Td.A1", "Td.A2", "Td.Ea", "Td.Eb"]
        @test (@test_logs (:warn,) names(cs, "N")) == ["D2h.Ag", "D2h.Au", "D2h.B1g", "D2h.B1u", "D2h.B2g", "D2h.B2u", "D2h.B3g", "D2h.B3u"]
        cs = symmetries(FiniteLattice(fcc, [-2 2 2; 2 -2 2; 2 2 -2], true); origin=o(fcc))
        @test (@test_logs (:warn,) names(cs, "L")) == ["D3d.A1g", "D3d.A1u", "D3d.A2g", "D3d.A2u", "D3d.Ega", "D3d.Egb", "D3d.Eua", "D3d.Eub"]
        @test (@test_logs (:warn,) names(cs, "W")) == ["D2d.A1", "D2d.A2", "D2d.B1", "D2d.B2", "D2d.Ea", "D2d.Eb"]
        cs = symmetries(FiniteLattice(simple_hexagonal, [3 0 0; 0 3 0; 0 0 3], true); origin=o(simple_hexagonal))
        @test names(cs, "K") == ["D3h.A1p", "D3h.A1pp", "D3h.A2p", "D3h.A2pp", "D3h.Epa", "D3h.Epb", "D3h.Eppa", "D3h.Eppb"]
        @test names(cs, "Gamma") == ["D6h.A1g", "D6h.A1u", "D6h.A2g", "D6h.A2u", "D6h.B1g", "D6h.B1u", "D6h.B2g", "D6h.B2u",
                                     "D6h.E1ga", "D6h.E1gb", "D6h.E1ua", "D6h.E1ub", "D6h.E2ga", "D6h.E2gb", "D6h.E2ua", "D6h.E2ub"]

        # Bilbao 6/mmm: B1g is even under the twofold axes 2_120 (perpendicular to a, b or a + b),
        # odd under 2_100 (along a, b or a + b)
        lattice = simple_hexagonal
        ops = operations(cs.spacegroup)
        B1g = only(irrep for irrep in irreps(cs) if irrep.label == "Gamma.D6h.B1g")
        a, b = lattice.A[1, :], lattice.A[2, :]
        for (j, opindex) in enumerate(cs.operations)
            R = lattice.A' * ops[opindex].W / lattice.A'
            (det(R) > 0 && round(Int, tr(R)) == -1 && iszero(cs.translations[j])) || continue
            axis = nullspace(R - I)[:, 1]
            abs(axis[3]) > 1e-8 && continue                      # the twofold axis along c
            χ = B1g.characters[findfirst(==(cs.permutation_index[j]), B1g.allowed_symmetries)]
            along_100 = any(v -> norm(cross(axis, v)) < 1e-8, [a, b, a + b])
            @test χ ≈ (along_100 ? -1 : 1)
        end

        # TOML with skipped three-dimensional irreps: banner at the top and in the irreps section
        fl = FiniteLattice(bcc, 2 * [0 1 1; 1 0 1; 1 1 0], true)
        s = @test_logs (:warn, r"skipped") write_toml(fl, neighbor_interaction("SdotS", "J", fl), ""; zero_based=true, return_string=true, symmetries=true)
        @test count("WARNING: three-dimensional irreducible representations were SKIPPED", s) == 2
        @test findfirst("SKIPPED", s)[1] < findfirst("Coordinates", s)[1]
        data = TOML.parse(s)
        @test haskey(data["P"]["Td"], "Ea") && !haskey(data["P"]["Td"], "T1")
        # no banner without three-dimensional irreps
        fl = FiniteLattice(simple_hexagonal, [3 0 0; 0 3 0; 0 0 2], true)
        s = @test_logs write_toml(fl, neighbor_interaction("SdotS", "J", fl), ""; zero_based=true, return_string=true,
                                  symmetries=true, origin=o(simple_hexagonal))
        @test !occursin("SKIPPED", s) && haskey(TOML.parse(s)["K"]["D3h"], "A1p")
    end

    @testset "sector dimensions" begin
        # ground-state sectors (S^z = 0, even under the spin flip) of the square lattice with 36 and
        # 40 sites, from J. Richter and J. Schulenburg, arXiv:0909.3723
        cs = symmetries(FiniteLattice(square, [6 0; 0 6], true); origin=site_origin(square))
        @test sector_dimension(cs, only(i for i in irreps(cs) if i.label == "Gamma.C4v.A1"); nup=18, spinflip=1) == 15804956
        cs = symmetries(FiniteLattice(square, [6 2; -2 6], true); origin=site_origin(square))
        @test sector_dimension(cs, only(i for i in irreps(cs) if i.label == "Gamma.C4.A"); nup=20, spinflip=1) == 430909650

        # exact dimensions agree with the floating-point reference and add up for every S^z;
        # the spin flip splits the sectors
        for (lattice, boundary, origin, _, _, _) in IRREP_CASES
            fl = FiniteLattice(lattice, boundary, true)
            cs = symmetries(fl; origin=origin)
            ks = momenta(cs)
            N = length(atoms(fl))
            starsize = Dict(k.label => count(q -> q.star == k.star, ks) for k in ks if k.representative)
            irs = irreps(cs)
            @test all(irrep -> sector_dimension(cs, irrep) == round(Int, real(reference_dimension(cs, irrep))), irs)
            @test all(nup -> sum(starsize[irrep.kpoint] * sector_dimension(cs, irrep; nup) for irrep in irs) == binomial(N, nup), 0:N)
            @test all(irrep -> sector_dimension(cs, irrep; spinflip=1) + sector_dimension(cs, irrep; spinflip=-1) == sector_dimension(cs, irrep), irs)
            if iseven(N)
                m = N ÷ 2
                @test all(irrep -> sector_dimension(cs, irrep; nup=m, spinflip=1) + sector_dimension(cs, irrep; nup=m, spinflip=-1) ==
                                   sector_dimension(cs, irrep; nup=m), irs)
            end
        end

        cs = symmetries(FiniteLattice(triangular, [3 0; 0 3], true))   # 9 sites
        irrep = first(irreps(cs))
        @test_throws ArgumentError sector_dimension(cs, irrep; nup=10)
        @test_throws ArgumentError sector_dimension(cs, irrep; nup=4, spinflip=1)
        @test_throws ArgumentError sector_dimension(cs, irrep; spinflip=2)
    end

    @testset "consistency check of the sectors" begin
        # run whenever the sectors are computed, e.g. by irreps and write_toml
        cs = symmetries(FiniteLattice(triangular, [3 0; 0 3], true))
        ks = momenta(cs)
        sectors = Latlib._sectors(cs)
        @test Latlib._check_sectors(cs, ks, sectors) === nothing
        # a missing sector
        @test_throws ErrorException Latlib._check_sectors(cs, ks, sectors[2:end])
        # characters that do not form a representation
        irrep, status = sectors[2]
        χ = copy(irrep.characters)
        χ[2] = -χ[2]
        broken = Irrep(irrep.label, irrep.kpoint, irrep.littlegroup, irrep.name, irrep.parent, irrep.dimension,
                       irrep.momentum, irrep.allowed_symmetries, χ)
        @test_throws ErrorException Latlib._check_sectors(cs, ks, [j == 2 ? (broken, status) : s for (j, s) in enumerate(sectors)])
        # the same sector twice
        @test_throws ErrorException Latlib._check_sectors(cs, ks, vcat(sectors, sectors[1:1]))
    end

    @testset "covariance of the names" begin
        tetragonal = Lattice([1.0 0 0; 0 1 0; 0 0 1.7])
        orthorhombic = Lattice([1.0 0 0; 0 1.3 0; 0 0 1.7])
        cases = [(triangular, [3 0; 0 3], nothing), (triangular, [4 -2; 2 2], nothing), (kagome, [3 0; 0 3], nothing),
                 (honeycomb, [2 -2; 1 1], nothing), (square, [6 0; 0 6], site_origin(square)), (square, [6 0; 0 4], site_origin(square)),
                 (maple_leaf, [1 1; 1 -2], nothing),
                 (simple_cubic, [4 0 0; 0 4 0; 0 0 4], site_origin3(simple_cubic)), (simple_cubic, [4 0 0; 0 4 0; 0 0 2], site_origin3(simple_cubic)),
                 (bcc, 3 * [0 1 1; 1 0 1; 1 1 0], nothing), (fcc, [4 0 0; 0 4 0; 0 0 4], site_origin3(fcc)),
                 (simple_hexagonal, [4 0 0; 0 4 0; 0 0 2], site_origin3(simple_hexagonal)),
                 (simple_hexagonal, [4 0 0; 0 2 0; 0 0 2], site_origin3(simple_hexagonal)),
                 (tetragonal, [4 0 0; 0 2 0; 0 0 3], site_origin3(tetragonal)), (orthorhombic, [4 0 0; 0 4 0; 0 0 4], site_origin3(orthorhombic))]
        for (lattice, boundary, origin) in cases
            @test names_covariant(symmetries(FiniteLattice(lattice, boundary, true); origin=origin))
        end
    end

    @testset "invariance under the description of the cluster" begin
        same(fl1, fl2; origin1=nothing, origin2=nothing) =
            fingerprint(symmetries(fl1; origin=origin1)) == fingerprint(symmetries(fl2; origin=origin2))
        R2(θ) = [cos(θ) -sin(θ); sin(θ) cos(θ)]
        R3 = let a = normalize([1.0, 2.0, 0.5]), K = [0 -a[3] a[2]; a[3] 0 -a[1]; -a[2] a[1] 0]
            I + sin(0.7) * K + (1 - cos(0.7)) * K^2
        end
        U2 = [1 0; 1 1]          # new lattice vectors (rows) in the old basis
        U3 = [1 0 0; 1 1 0; 0 1 1]
        relabel(lattice, U) = Lattice(U * lattice.A, lattice.positions / U)
        rebound(boundary, U) = round.(Int, boundary / U)

        # same torus, other boundary vectors
        o = site_origin(square)
        @test same(FiniteLattice(square, [4 0; 0 4], true), FiniteLattice(square, [4 0; 4 4], true); origin1=o, origin2=o)
        # other primitive basis of the lattice
        for (lattice, boundary) in [(triangular, [3 0; 0 3]), (honeycomb, [3 0; 0 3]), (kagome, [2 0; 0 2])]
            @test same(FiniteLattice(lattice, boundary, true), FiniteLattice(relabel(lattice, U2), rebound(boundary, U2), true))
        end
        @test same(FiniteLattice(triangular, [3 0; 0 3], true), FiniteLattice(Lattice([1.0 0; -0.5 sqrt(3) / 2]), [3 0; 0 3], true))
        @test same(FiniteLattice(bcc, 2 * [0 1 1; 1 0 1; 1 1 0], true), FiniteLattice(relabel(bcc, U3), rebound(2 * [0 1 1; 1 0 1; 1 1 0], U3), true))
        for (lattice, boundary) in [(fcc, [-2 2 2; 2 -2 2; 2 2 -2]), (simple_hexagonal, [3 0 0; 0 3 0; 0 0 2])]
            @test same(FiniteLattice(lattice, boundary, true), FiniteLattice(relabel(lattice, U3), rebound(boundary, U3), true);
                       origin1=site_origin3(lattice), origin2=site_origin3(relabel(lattice, U3)))
        end
        # rotated lattices, unit cell shifted
        @test same(FiniteLattice(kagome, [2 0; 0 2], true), FiniteLattice(Lattice(kagome.A * R2(0.3)', kagome.positions), [2 0; 0 2], true))
        @test same(FiniteLattice(maple_leaf, [1 1; 1 -2], true), FiniteLattice(Lattice(maple_leaf.A, maple_leaf.positions .+ [0.1 0.23]), [1 1; 1 -2], true))
        @test same(FiniteLattice(bcc, 2 * [0 1 1; 1 0 1; 1 1 0], true), FiniteLattice(Lattice(bcc.A * R3'), 2 * [0 1 1; 1 0 1; 1 1 0], true))
        rotated = Lattice(simple_hexagonal.A * R3')
        @test same(FiniteLattice(simple_hexagonal, [3 0 0; 0 3 0; 0 0 2], true), FiniteLattice(rotated, [3 0 0; 0 3 0; 0 0 2], true);
                   origin1=site_origin3(simple_hexagonal), origin2=site_origin3(rotated))
        # tetragonal lattice with its fourfold axis along x instead of z
        tz, tx = Lattice([1.0 0 0; 0 1 0; 0 0 1.7]), Lattice([1.7 0 0; 0 1 0; 0 0 1])
        @test same(FiniteLattice(tz, [2 0 0; 0 2 0; 0 0 3], true), FiniteLattice(tx, [3 0 0; 0 2 0; 0 0 2], true);
                   origin1=site_origin3(tz), origin2=site_origin3(tx))

        # order of the sites: same characters on the relabelled permutations
        fl1 = FiniteLattice(maple_leaf, [1 1; 1 -2], true)
        fl2 = FiniteLattice(maple_leaf, [1 1; 1 -2], true; bravais_order=order_yx, atom_order=order_xy)
        cs1, cs2 = symmetries(fl1), symmetries(fl2)
        x1, x2 = [x.coords for x in atoms(fl1)], [x.coords for x in atoms(fl2)]
        σ = [findfirst(y -> isapprox(y, x; atol=1e-8), x2) for x in x1]
        @test sort(σ) == eachindex(x2) && σ != eachindex(x2)
        relabelled(p) = (q = similar(p); q[σ] = σ[p]; q)
        table(cs, irrep, f) = Dict(f(cs.permutations[i]) => χ for (i, χ) in zip(irrep.allowed_symmetries, irrep.characters))
        tables1 = Dict(irrep.label => table(cs1, irrep, relabelled) for irrep in irreps(cs1))
        tables2 = Dict(irrep.label => table(cs2, irrep, identity) for irrep in irreps(cs2))
        @test keys(tables1) == keys(tables2)
        @test all(label -> keys(tables1[label]) == keys(tables2[label]) &&
                           all(p -> isapprox(tables1[label][p], tables2[label][p]; atol=1e-12), keys(tables1[label])), keys(tables1))
    end
end
