using LinearAlgebra
using TOML

# This file tests the irreducible representations of the symmetry groups of finite
# lattices (src/symmetry/pointgroups.jl, kpoints.jl, irreps.jl) and their TOML output.
#
# Besides hand-derived expectations for the momenta, every cluster is checked with
# group-theoretical identities that do not rely on the implementation:
#  - the characters of each sector are multiplicative on its group (as checked by XDiag),
#  - the dimension of each sector in the spin-1/2 Hilbert space, from the character formula
#    dim = (1/|S|) Σ_s conj(χ(s)) 2^(number of cycles of s), is a non-negative integer,
#  - completeness: Σ_stars |star| Σ_sectors dim = 2^N.
# The characters are also compared with the legacy maple-leaf files, which were generated by
# an independent code.


# number of cycles of a permutation
function ncycles(p::Vector{Int})
    seen = falses(length(p))
    n = 0
    for i in eachindex(p)
        seen[i] && continue
        n += 1
        j = i
        while !seen[j]
            seen[j] = true
            j = p[j]
        end
    end
    return n
end

# dimension of a sector in the spin-1/2 Hilbert space
function sector_dimension(cs::ClusterSymmetries, irrep::Irrep)
    P = cs.permutations
    d = sum(conj(χ) * 2.0^ncycles(P[i]) for (i, χ) in zip(irrep.allowed_symmetries, irrep.characters))
    return d / length(irrep.allowed_symmetries)
end

function characters_multiplicative(cs::ClusterSymmetries, irrep::Irrep)
    P = cs.permutations
    index = Dict(p => i for (i, p) in enumerate(P))
    χ = Dict(zip(irrep.allowed_symmetries, irrep.characters))
    for i in irrep.allowed_symmetries, j in irrep.allowed_symmetries
        ij = index[P[i][P[j]]]   # first j, then i
        (haskey(χ, ij) && isapprox(χ[ij], χ[i] * χ[j]; atol=1e-10)) || return false
    end
    return true
end

site_origin(lattice) = LatticeVector(lattice, [0.0, 0.0])
const rectangular = Lattice([1.0 0.0; 0.0 1.5])
const trellis_origin = LatticeVector(trellis, spacegroup(trellis).origin)

# (lattice, boundary, origin, representatives "label.littlegroup" (sorted), number of sectors, number of vanishing sectors)
const IRREP_CASES = [
    (maple_leaf,  [1 1; 1 -2],  nothing,                 ["Gamma.C6", "K.C3"], 9, 0),
    (maple_leaf,  [1 0; 0 2],   nothing,                 ["Gamma.C2", "M.C2"], 4, 0),
    (triangular,  [3 0; 0 3],   nothing,                 ["Gamma.C6v", "K.C3v", "Sigma.Cs"], 14, 0),
    (triangular,  [2 0; 0 1],   nothing,                 ["Gamma.C2v", "M.C2v"], 2, 6),          # two sites
    (triangular,  [3 1; -1 4],  nothing,                 ["GP0.C1", "GP1.C1", "Gamma.C6"], 8, 0),  # 13 sites, chiral
    (honeycomb,   [3 0; 0 3],   nothing,                 ["Gamma.C6v", "K.C3v", "Sigma.Cs"], 14, 0),
    (honeycomb,   [2 -2; 1 1],  nothing,                 ["Gamma.C2v", "Lambda.Cs", "M.C2v"], 10, 0),
    (kagome,      [2 0; 0 2],   nothing,                 ["Gamma.C6v", "M.C2v"], 12, 0),
    (square,      [4 0; 0 4],   site_origin(square),     ["Delta.Cs", "Gamma.C4v", "M.C4v", "Sigma.Cs", "X.C2v", "Y.Cs"], 22, 0),
    (square,      [4 0; 0 2],   site_origin(square),     ["Delta.Cs", "Gamma.C2v", "M.C2v", "X0.C2v", "X1.C2v", "Y.Cs"], 10, 10),  # mirror y -> -y trivial
    (square,      [3 1; -1 3],  site_origin(square),     ["GP0.C1", "GP1.C1", "Gamma.C4", "M.C4"], 10, 0),
    (lieb,        [2 0; 0 2],   site_origin(lieb),       ["Gamma.C4v", "M.C4v", "X.C2v"], 16, 0),
    (trellis,     [4 0; -2 4],  trellis_origin,          ["C.Cs", "Delta.Cs", "GP0.C1", "Gamma.C2v", "S.C2", "Sigma0.Cs", "Sigma1.Cs", "Y.C2v"], 19, 0),
    (trellis,     [3 0; 1 2],   trellis_origin,          ["GP0.C1", "GP1.C1", "Gamma.C2", "Y.C2"], 6, 0),
    (rectangular, [4 0; 0 4],   site_origin(rectangular), ["C.Cs", "D.Cs", "Delta.Cs", "GP0.C1", "Gamma.C2v", "S.C2v", "Sigma.Cs", "X.C2v", "Y.C2v"], 25, 0),
    (rectangular, [2 0; 0 3],   site_origin(rectangular), ["D.Cs", "Delta.Cs", "Gamma.C2v", "X.C2v"], 6, 6),  # mirror x -> -x trivial
]

const LEGACY_FILES = ["maple.leaf.JhexagonJtriangleJdimer.12.v1.2sl.toml",
                      "maple.leaf.JhexagonJtriangleJdimer.18.v1.2sl.toml",
                      "maple.leaf.JhexagonJtriangleJdimer.24.v2.2sl.toml",
                      "maple.leaf.JhexagonJtriangleJdimer.36.v3.2sl.toml",
                      "maple.leaf.JhexagonJtriangleJdimer.54.v1.2sl.toml"]


@testset "Irreducible representations" begin

    @testset "point groups" begin
        # irrep names of the little co-groups at Gamma of lattices with full symmetry
        names(cs) = sort([irrep.name for irrep in irreps(cs) if irrep.kpoint == "Gamma"])
        @test names(symmetries(FiniteLattice(triangular, [3 0; 0 3], true))) == ["A1", "A2", "B1", "B2", "E1a", "E1b", "E2a", "E2b"]
        @test names(symmetries(FiniteLattice(maple_leaf, [1 1; 1 -2], true))) == ["A", "B", "E1a", "E1b", "E2a", "E2b"]
        @test names(symmetries(FiniteLattice(square, [4 0; 0 4], true); origin=site_origin(square))) == ["A1", "A2", "B1", "B2", "Ea", "Eb"]
        @test names(symmetries(FiniteLattice(square, [3 1; -1 3], true); origin=site_origin(square))) == ["A", "B", "Ea", "Eb"]
        @test names(symmetries(FiniteLattice(rectangular, [4 0; 0 4], true); origin=site_origin(rectangular))) == ["A1", "A2", "B1", "B2"]
        @test sort(unique(irrep.name for irrep in irreps(symmetries(FiniteLattice(triangular, [3 0; 0 3], true))) if irrep.kpoint == "K")) == ["A1", "A2", "Ea", "Eb"]
        @test sort(unique(irrep.name for irrep in irreps(symmetries(FiniteLattice(triangular, [3 0; 0 3], true))) if irrep.kpoint == "Sigma")) == ["Ap", "App"]

        # Bilbao conventions for B1/B2 at Gamma of C6v: B1 is even under mirrors whose normal is a lattice vector
        cs = symmetries(FiniteLattice(triangular, [3 0; 0 3], true))
        B1 = only(irrep for irrep in irreps(cs) if irrep.label == "Gamma.C6v.B1")
        ops = operations(cs.spacegroup)
        for (j, opindex) in enumerate(cs.operations)
            W = ops[opindex].W
            R = triangular.A' * W / triangular.A'
            (det(R) < 0 && iszero(cs.translations[j])) || continue
            normal = nullspace(R + I)[:, 1]
            normal_is_lattice_vector = any(v -> abs(normal[1] * v[2] - normal[2] * v[1]) < 1e-8,
                                           [triangular.A' * [1, 0], triangular.A' * [0, 1], triangular.A' * [1, -1]])
            χ = B1.characters[findfirst(==(cs.permutation_index[j]), B1.allowed_symmetries)]
            @test χ ≈ (normal_is_lattice_vector ? 1 : -1)
        end

        # two-dimensional irreps of C6v: partners a/b on C6 are complex conjugate at Gamma
        E1a = only(irrep for irrep in irreps(cs) if irrep.label == "Gamma.C6v.E1a")
        E1b = only(irrep for irrep in irreps(cs) if irrep.label == "Gamma.C6v.E1b")
        @test E1a.parent == "E1" && E1a.dimension == 2
        @test E1a.allowed_symmetries == E1b.allowed_symmetries
        @test E1a.characters ≈ conj.(E1b.characters)
        @test length(E1a.allowed_symmetries) == 6 * 9   # C6 times translations
        @test sector_dimension(cs, E1a) ≈ sector_dimension(cs, E1b)
        # complex one-dimensional irreps of C6 are not split
        cs6 = symmetries(FiniteLattice(maple_leaf, [1 1; 1 -2], true))
        @test all(irrep -> irrep.dimension == 1 && irrep.parent == irrep.name, irreps(cs6))
    end

    @testset "momenta and sectors" begin
        for (lattice, boundary, origin, representatives, nsectors, nvanishing) in IRREP_CASES
            fl = FiniteLattice(lattice, boundary, true)
            cs = symmetries(fl; origin=origin)
            ks = momenta(cs)
            N = length(atoms(fl))

            # momenta: one per Bravais cell, stars partition them, one representative per star
            @test length(ks) == length(bravais_cells(fl))
            @test count(k -> k.representative, ks) == length(unique(k.star for k in ks))
            @test sort(["$(k.label).$(k.littlegroup_name)" for k in ks if k.representative]) == representatives
            @test all(k -> k.label == first(q.label for q in ks if q.star == k.star), ks)

            # sectors
            irs = irreps(cs)
            @test length(irs) == nsectors
            @test length(Latlib._sectors(cs)) == nsectors + nvanishing
            @test allunique(irrep.label for irrep in irs)
            @test all(irrep -> irrep.allowed_symmetries[1] == 1 && irrep.characters[1] ≈ 1, irs)
            @test all(irrep -> characters_multiplicative(cs, irrep), irs)
            @test allunique(cs.permutations)
            @test cs.permutations[1] == collect(1:N)

            # dimensions are non-negative integers and add up to the full Hilbert space
            starsize = Dict(k.label => count(q -> q.star == k.star, ks) for k in ks if k.representative)
            dims = [sector_dimension(cs, irrep) for irrep in irs]
            @test all(d -> abs(imag(d)) < 1e-6 && abs(real(d) - round(real(d))) < 1e-6 && real(d) > -1e-6, dims)
            @test round(Int, sum(starsize[irrep.kpoint] * real(d) for (irrep, d) in zip(irs, dims))) == 2^N
        end
    end

    @testset "symmetry center" begin
        fl = FiniteLattice(square, [4 0; 0 4], true)
        # ambiguous for the square lattice: site or plaquette center
        @test_throws ArgumentError symmetries(fl)
        err = try symmetries(fl) catch e e end
        @test occursin("ambiguous", err.msg) && occursin("(1/2, 1/2)", err.msg)
        # not a point with the full point-group symmetry
        @test_throws ArgumentError symmetries(fl; origin=LatticeVector(square, [0.5, 0.0]))
        # unique for hexagonal lattices: hexagon centers of honeycomb and kagome
        @test symmetries(FiniteLattice(honeycomb, [3 0; 0 3], true)).origin ≈ [2/3, 2/3]
        @test symmetries(FiniteLattice(kagome, [2 0; 0 2], true)).origin ≈ [1/2, 1/2]
        # origin as EuclideanVector
        @test symmetries(fl; origin=EuclideanVector([0.5, 0.5])).origin ≈ [0.5, 0.5]

        # the two centers give the same sectors at M, with different labels
        cs1 = symmetries(fl; origin=LatticeVector(square, [0.0, 0.0]))
        cs2 = symmetries(fl; origin=LatticeVector(square, [0.5, 0.5]))
        @test cs1.permutations == cs2.permutations
        sectors_at_M(cs) = Dict(irrep.name => Dict(zip(irrep.allowed_symmetries, irrep.characters)) for irrep in irreps(cs) if irrep.kpoint == "M")
        M1, M2 = sectors_at_M(cs1), sectors_at_M(cs2)
        @test Set(values(M1)) == Set(values(M2))
        @test any(name -> M1[name] != M2[name], keys(M1))
        # but not at Gamma
        sectors_at_Γ(cs) = Dict(irrep.name => irrep.characters for irrep in irreps(cs) if irrep.kpoint == "Gamma")
        @test sectors_at_Γ(cs1) == sectors_at_Γ(cs2)
    end

    @testset "unsupported cases" begin
        @test_throws ArgumentError symmetries(FiniteLattice(shastry_sutherland_non_symmorphic, [2 0; 0 2], true))   # p4gm
        @test_throws ArgumentError symmetries(FiniteLattice(simple_cubic, [2 0 0; 0 2 0; 0 0 2], true))           # 3D
        @test_throws ArgumentError symmetries(FiniteLattice(triangular, [3 0; 0 3], [true, false]))              # open
        # non-primitive unit cell: only translations by lattice vectors are used
        fl = FiniteLattice(shastry_sutherland, [2 0; 0 2], true)
        cs = @test_logs (:warn, r"not primitive") symmetries(fl; origin=site_origin(shastry_sutherland))
        @test length(cs.operations) == 8 * 4
        @test length(cs.operations) < length(cs.spacegroup)
    end

    @testset "legacy maple-leaf files" begin
        parse_vector(text, name) = parse.(Float64, split(match(Regex(name * raw"=\(([^)]*)\)"), text)[1], ","))
        # Bilbao labels replace the labels of the legacy code for lines and generic momenta
        legacy_base(label) = (m = match(r"^([A-Za-z]*)\d*$", label); base = m[1];
                              base == "" ? "GP" : base == "X" ? "Lambda" : base == "Y" ? "Sigma" : base == "Z" ? "T" : base)
        for file in LEGACY_FILES
            @testset "$file" begin
                path = joinpath(@__DIR__, "data", "legacy", file)
                text = read(path, String)
                data = TOML.parsefile(path)
                t = hcat(parse_vector(text, "t1"), parse_vector(text, "t2"))
                fl = FiniteLattice(maple_leaf, round.(Int, (maple_leaf.A' \ t)'), true)
                cs = symmetries(fl)
                ours = irreps(cs)

                # map legacy sites onto ours by position modulo the torus
                T = Matrix{Float64}(fl.boundary')
                X = [maple_leaf.A' \ x.coords for x in atoms(fl)]
                same(x, y) = (u = T \ (x - y); norm(u - round.(u)) < 1e-6)
                σ = [findfirst(y -> same(maple_leaf.A' \ Float64.(c), y), X) for c in data["Coordinates"]]
                legacy_perm(q) = (p = zeros(Int, length(q)); for i in eachindex(q); p[σ[i]] = σ[q[i] + 1]; end; p)

                legacy_labels = String[]
                for (k, v) in data, (gname, v2) in (v isa Dict ? v : Dict()), (name, rep) in v2
                    push!(legacy_labels, k)
                    # duplicate representative of the legacy code (see roadmap §1.4): K1 ~ K0 in 36.v3
                    (occursin("36.v3", file) && k == "K1") && continue
                    κ = maple_leaf.A * Float64.(rep["momentum"]) / 2π
                    match_ = [ir for ir in ours if ir.name == name && ir.littlegroup == gname &&
                              (d = maple_leaf.A * ir.momentum / 2π - κ; norm(d - round.(d)) < 1e-6)]
                    @test length(match_) == 1
                    isempty(match_) && continue
                    ir = match_[1]
                    @test legacy_base(k) == match(r"^([A-Za-z]*)\d*$", ir.kpoint)[1]
                    ourχ = Dict(cs.permutations[i] => χ for (i, χ) in zip(ir.allowed_symmetries, ir.characters))
                    legχ = Dict(legacy_perm(data["Symmetries"][s + 1]) => complex(c...) for (s, c) in zip(rep["allowed_symmetries"], rep["characters"]))
                    @test keys(ourχ) == keys(legχ)
                    @test all(p -> isapprox(ourχ[p], legχ[p]; atol=1e-12), collect(keys(legχ)))
                end
                # every sector of ours is in the legacy file (up to the merged duplicate)
                @test length(ours) == count(l -> !(occursin("36.v3", file) && l == "K1"), legacy_labels)
            end
        end
    end

    @testset "TOML output" begin
        # maple leaf, 18 sites: same sections as the legacy file
        fl = FiniteLattice(maple_leaf, [1 1; 1 -2], true)
        H = neighbor_interaction("SdotS", "J", fl)
        cs = symmetries(fl)
        s = write_toml(fl, H, ""; zero_based=true, return_string=true, symmetries=true)
        @test s == write_toml(fl, H, ""; zero_based=true, return_string=true, symmetries=cs)
        data = TOML.parse(s)
        @test data["Symmetries"] == [p .- 1 for p in cs.permutations]
        legacy = TOML.parsefile(joinpath(@__DIR__, "data", "legacy", LEGACY_FILES[2]))
        labels(d) = Set("$k.$g.$i" for (k, v) in d if v isa Dict for (g, v2) in v for (i, _) in v2)
        @test labels(data) == labels(legacy)
        for irrep in irreps(cs)
            k, g, i = split(irrep.label, ".")
            section = data[k][g][i]
            @test section["allowed_symmetries"] == irrep.allowed_symmetries .- 1
            @test [complex(c...) for c in section["characters"]] ≈ irrep.characters
            @test section["momentum"] ≈ irrep.momentum
        end
        @test occursin("# Symmetry center: (3/7, 5/7)", s)
        @test occursin("#   K        C3    (1.5832138823, 0.0000000000) *", s)
        @test !occursin("PLACEHOLDER", s)

        # two-dimensional irreps are marked
        fl3 = FiniteLattice(triangular, [3 0; 0 3], true)
        s3 = write_toml(fl3, neighbor_interaction("SdotS", "J", fl3), ""; zero_based=true, return_string=true, symmetries=true)
        @test occursin("# Gamma.C6v.E1 is two-dimensional", s3)
        @test haskey(TOML.parse(s3)["Gamma"]["C6v"], "E1a")

        # thin cluster: omitted operations and vanishing irreps are reported
        fl2 = FiniteLattice(square, [4 0; 0 2], true)
        H2 = neighbor_interaction("SdotS", "J", fl2)
        @test_throws ArgumentError write_toml(fl2, H2, ""; zero_based=true, return_string=true, symmetries=true)   # ambiguous center
        cs2 = symmetries(fl2; origin=site_origin(square))
        s2 = write_toml(fl2, H2, ""; zero_based=true, return_string=true, symmetries=cs2)
        data2 = TOML.parse(s2)
        @test length(data2["Symmetries"]) == 16
        @test occursin("PLACEHOLDER (TOML format to be decided): omitted symmetry operations", s2)
        @test occursin("PLACEHOLDER (TOML format to be decided): omitted irreducible representations", s2)
        @test occursin("#   Gamma.C2v.B2\n", s2)
        @test !haskey(data2["Gamma"]["C2v"], "B2")
        @test haskey(data2["Gamma"]["C2v"], "A1")
    end

    @testset "write_toml for all space groups" begin
        toml(fl; kwargs...) = write_toml(fl, neighbor_interaction("SdotS", "J", fl), ""; zero_based=true, return_string=true, kwargs...)

        # symmorphic, unique symmetry center: irreps are written automatically
        fl = FiniteLattice(triangular, [3 0; 0 3], true)
        s = @test_logs toml(fl; symmetries=true)
        @test occursin("# Irreducible representations\n", s)
        @test s == toml(fl; symmetries=spacegroup(fl)) == toml(fl; symmetries=symmetries(fl))
        # ... unless irreps=false
        s_noirreps = @test_logs toml(fl; symmetries=true, irreps=false)
        @test !occursin("# Irreducible representations\n", s_noirreps)
        @test TOML.parse(s_noirreps)["Symmetries"] == TOML.parse(s)["Symmetries"]
        s_cs = toml(fl; symmetries=symmetries(fl), irreps=false)
        @test haskey(TOML.parse(s_cs), "Symmetries") && !occursin("# Irreducible representations\n", s_cs)

        # symmorphic, ambiguous symmetry center: `origin` is needed for irreps, but not without them
        fl = FiniteLattice(square, [4 0; 0 4], true)
        @test_throws ArgumentError toml(fl; symmetries=true)
        s_origin = toml(fl; symmetries=true, origin=site_origin(square))
        @test s_origin == toml(fl; symmetries=symmetries(fl; origin=site_origin(square)))
        @test occursin("[M.C4v.A1]", s_origin)
        s_noirreps = @test_logs toml(fl; symmetries=true, irreps=false)
        @test length(TOML.parse(s_noirreps)["Symmetries"]) == 128
        @test_throws ArgumentError toml(fl; symmetries=symmetries(fl; origin=site_origin(square)), origin=site_origin(square))

        # non-symmorphic: only the symmetry operations, with a warning
        for (lattice, boundary, nperms) in [(shastry_sutherland_non_symmorphic, [2 0; 0 2], 32),   # p4gm
                                            (diamond, [-1 1 1; 1 -1 1; 1 1 -1], 192),           # Fd-3m
                                            (hcp, [3 0 0; 0 3 0; 0 0 2], 432)]                   # P6_3/mmc
            fl = FiniteLattice(lattice, boundary, true)
            s = @test_logs (:warn, r"not implemented for non-symmorphic space groups") toml(fl; symmetries=true)
            data = TOML.parse(s)
            @test length(data["Symmetries"]) == nperms
            @test data["Symmetries"] == [p .- 1 for p in site_permutations(spacegroup(fl))[distinct_operations(spacegroup(fl))]]
            @test !occursin("# Irreducible representations\n", s)
            # no warning if irreps are not requested
            @test (@test_logs toml(fl; symmetries=true, irreps=false)) == s
        end

        # three-dimensional symmorphic: only the symmetry operations, with a warning
        fl = FiniteLattice(simple_cubic, [2 0 0; 0 2 0; 0 0 2], true)
        s = @test_logs (:warn, r"not implemented for three-dimensional lattices") toml(fl; symmetries=true)
        @test length(TOML.parse(s)["Symmetries"]) == 48
        @test occursin("PLACEHOLDER (TOML format to be decided): omitted symmetry operations", s)
        @test !occursin("# Irreducible representations\n", s)
    end
end
