using LinearAlgebra

# ----------------------------------------------------------------------
#      Finite groups of integer matrices and their irreducible
#      representations of dimension one and two
# ----------------------------------------------------------------------
#
# One-dimensional representations of crystallographic point groups take
# values in the 12th roots of unity. They are stored exactly as exponents
# a(g) ∈ {0, ..., 11} with χ(g) = exp(2πi a(g) / 12).

struct _FiniteGroup
    elements::Vector{Matrix{Int}}   # the identity comes first
    table::Matrix{Int}              # table[i, j] = index of elements[i] * elements[j]
    inverse::Vector{Int}
end

function _FiniteGroup(elements::Vector{Matrix{Int}})
    elements = vcat(filter(W -> W == I, elements), filter(W -> W != I, elements))
    length(elements) >= 1 && elements[1] == I || error("The identity is not part of the group.")
    index = Dict(W => i for (i, W) in enumerate(elements))
    n = length(elements)
    table = zeros(Int, n, n)
    for i in 1:n, j in 1:n
        table[i, j] = get(index, elements[i] * elements[j], 0)
        table[i, j] == 0 && error("The matrices do not form a group. This is a bug, please report!")
    end
    inverse = [findfirst(j -> table[i, j] == 1, 1:n) for i in 1:n]
    return _FiniteGroup(elements, table, inverse)
end

Base.length(G::_FiniteGroup) = length(G.elements)

function _element_order(G::_FiniteGroup, g::Int) :: Int
    h, order = g, 1
    while h != 1
        h = G.table[g, h]
        order += 1
    end
    return order
end

# elements generated by `gens`
function _closure(G::_FiniteGroup, gens::Vector{Int}) :: Set{Int}
    span = Set([1])
    frontier = [1]
    while !isempty(frontier)
        new = Int[]
        for h in frontier, g in gens
            p = G.table[g, h]
            if !(p in span)
                push!(span, p)
                push!(new, p)
            end
        end
        frontier = new
    end
    return span
end

function _generators(G::_FiniteGroup) :: Vector{Int}
    gens = Int[]
    span = Set([1])
    while length(span) < length(G)
        push!(gens, first(i for i in 1:length(G) if !(i in span)))
        span = _closure(G, gens)
    end
    return gens
end

function _nclasses(G::_FiniteGroup) :: Int
    seen = falses(length(G))
    n = 0
    for g in 1:length(G)
        seen[g] && continue
        n += 1
        for x in 1:length(G)
            seen[G.table[G.table[x, g], G.inverse[x]]] = true
        end
    end
    return n
end

# all one-dimensional representations, as exponents modulo 12
function _irreps_1d(G::_FiniteGroup) :: Vector{Vector{Int}}
    n = length(G)
    gens = _generators(G)
    choices = [[a for a in 0:11 if mod(a * _element_order(G, g), 12) == 0] for g in gens]
    irreps = Vector{Int}[]
    for values in Iterators.product(choices...)
        # extend from the generators: a(g h) = a(g) + a(h)
        a = fill(-1, n)
        a[1] = 0
        frontier = [1]
        consistent = true
        while consistent && !isempty(frontier)
            new = Int[]
            for h in frontier, (k, g) in enumerate(gens)
                p = G.table[g, h]
                v = mod(values[k] + a[h], 12)
                if a[p] == -1
                    a[p] = v
                    push!(new, p)
                elseif a[p] != v
                    consistent = false
                end
            end
            frontier = new
        end
        consistent || continue
        all(mod(a[i] + a[j], 12) == a[G.table[i, j]] for i in 1:n, j in 1:n) || continue
        push!(irreps, a)
    end
    return irreps
end

_root(a::Integer) = cispi(a / 6)   # exp(2πi a / 12)

# A two-dimensional irreducible representation, induced from a one-dimensional
# representation of a subgroup of index two.
struct _Irrep2D
    character::Vector{ComplexF64}
    det::Vector{Int}                # determinant, as exponents modulo 12
end

function _subgroup(G::_FiniteGroup, indices::Vector{Int}) :: _FiniteGroup
    return _FiniteGroup(G.elements[sort(indices)])
end

# all two-dimensional irreducible representations
function _irreps_2d(G::_FiniteGroup, irreps1::Vector{Vector{Int}}) :: Vector{_Irrep2D}
    n = length(G)
    irreps = _Irrep2D[]
    for σ in irreps1
        # σ real and non-trivial: H = ker σ has index two
        (all(v -> v == 0 || v == 6, σ) && any(==(6), σ)) || continue
        Hidx = [i for i in 1:n if σ[i] == 0]
        H = _subgroup(G, Hidx)
        g0 = findfirst(==(6), σ)
        g0inv = G.inverse[g0]
        for ρH in _irreps_1d(H)
            ρ = Dict(Hidx[k] => ρH[k] for k in eachindex(Hidx))
            ρc = Dict(h => ρ[G.table[G.table[g0inv, h], g0]] for h in Hidx)   # h -> ρ(g0⁻¹ h g0)
            any(h -> ρ[h] != ρc[h], Hidx) || continue                           # induced representation reducible
            χ = zeros(ComplexF64, n)
            for h in Hidx
                χ[h] = _root(ρ[h]) + _root(ρc[h])
            end
            any(E -> isapprox(E.character, χ; atol=1e-8), irreps) && continue
            det = zeros(Int, n)
            for g in 1:n
                # basis e1, e2 = g0 e1: h -> diag(ρ(h), ρ(g0⁻¹ h g0)), g ∉ H -> [0 ρ(g g0); ρ(g0⁻¹ g) 0]
                det[g] = σ[g] == 0 ? mod(ρ[g] + ρc[g], 12) : mod(6 + ρ[G.table[g, g0]] + ρ[G.table[g0inv, g]], 12)
            end
            push!(irreps, _Irrep2D(χ, det))
        end
    end
    return irreps
end


# ----------------------------------------------------------------------
#             Two-dimensional crystallographic point groups
# ----------------------------------------------------------------------

_angle2d(R::AbstractMatrix) = mod(atan(R[2, 1], R[1, 1]), 2π)       # counter-clockwise angle of a rotation

function _mirror_line(R::AbstractMatrix) :: Vector{Float64}          # direction of the line of a reflection
    φ = atan(R[2, 1], R[1, 1]) / 2
    return [cos(φ), sin(φ)]
end

_mirror_normal(R::AbstractMatrix) = (u = _mirror_line(R); [-u[2], u[1]])

_parallel(u::AbstractVector, v::AbstractVector) = abs(u[1] * v[2] - u[2] * v[1]) < 1e-8 * norm(u) * norm(v)

# Schoenflies symbol of a two-dimensional point group from its Cartesian matrices
function _pointgroup_name_2d(Rs::Vector{<:AbstractMatrix}) :: String
    n = length(Rs)
    nmirrors = count(R -> det(R) < 0, Rs)
    nmirrors == 0 && return "C$n"
    return n == 2 ? "Cs" : "C$(n ÷ 2)v"
end

# name of the representation of the n-fold rotation group with χ(C_n⁺) = exp(2πi m/n)
function _cn_name(n::Int, m::Int) :: String
    m = mod(m, n)
    (n == 1 || m == 0) && return "A"
    2m == n && return "B"
    n == 6 && return "E" * string(min(m, n - m)) * (2m < n ? "a" : "b")
    return 2m < n ? "Ea" : "Eb"
end

# index of the rotation with the smallest positive counter-clockwise angle (nothing for C1/Cs)
function _principal_rotation(Rs::Vector{<:AbstractMatrix})
    rotations = [i for i in eachindex(Rs) if det(Rs[i]) > 0 && _angle2d(Rs[i]) > 1e-8]
    isempty(rotations) && return nothing
    return rotations[argmin([_angle2d(Rs[i]) for i in rotations])]
end

# exponent m of exp(2πi m / n) on the principal rotation of an n-fold rotation group
function _cn_exponent(a::Vector{Int}, Rs::Vector{<:AbstractMatrix}) :: Int
    r = _principal_rotation(Rs)
    isnothing(r) && return 0
    n = round(Int, 2π / _angle2d(Rs[r]))
    return a[r] * n ÷ 12
end

# Context needed to orient Mulliken labels (Bilbao conventions)
struct _NamingContext
    holohedry::Symbol                     # :oblique, :rectangular, :centered_rectangular, :square, :hexagonal
    conventional::Matrix{Float64}         # columns: conventional lattice vectors (Cartesian)
    shortest::Vector{Vector{Float64}}     # shortest lattice vectors (Cartesian)
    k::Union{Nothing, Vector{Float64}}    # momentum (Cartesian, first Brillouin zone); nothing at Γ
end

_normal_along_shortest(R, ctx::_NamingContext) = any(v -> _parallel(_mirror_normal(R), v), ctx.shortest)

# The mirror σ_v used for the subscripts 1/2 (B1 is even under σ_v):
#  - C6v and C2v of a hexagonal lattice: mirrors whose normal is a lattice vector (class m_100 of 6mm)
#  - C4v: axial mirrors, normal along a lattice vector (class m_100 of 4mm)
#  - C2v of a square lattice: the mirror leaving k invariant (k ≠ Γ), else the mirror along
#    the conventional axis a, else along a + b
#  - C2v of a (centered) rectangular lattice: the mirror whose line is along the conventional axis a,
#    as for m_y in the standard setting of mm2
function _sigma_v(Rs::Vector{<:AbstractMatrix}, ctx::_NamingContext) :: Int
    mirrors = [i for i in eachindex(Rs) if det(Rs[i]) < 0]
    a, b = ctx.conventional[:, 1], ctx.conventional[:, 2]
    along(v) = findfirst(i -> _parallel(_mirror_line(Rs[i]), v), mirrors)
    if ctx.holohedry == :hexagonal || length(mirrors) == 4
        i = findfirst(i -> _normal_along_shortest(Rs[i], ctx), mirrors)
    elseif ctx.holohedry == :square
        i = nothing
        if !isnothing(ctx.k)
            fixing = [j for j in eachindex(mirrors) if norm(Rs[mirrors[j]] * ctx.k - ctx.k) < 1e-8]
            length(fixing) == 1 && (i = fixing[1])
        end
        isnothing(i) && (i = along(a))
        isnothing(i) && (i = along(a + b))
    else
        i = along(a)
    end
    isnothing(i) && error("Could not orient the mirrors of the little co-group. This is a bug, please report!")
    return mirrors[i]
end

# Mulliken name of a one-dimensional representation (exponents `a`) of a 2D point group
function _name_1d(gname::String, a::Vector{Int}, Rs::Vector{<:AbstractMatrix}, ctx::_NamingContext) :: String
    if gname in ("C1", "C2", "C3", "C4", "C6")
        return _cn_name(parse(Int, gname[2:end]), _cn_exponent(a, Rs))
    end
    mirror = findfirst(R -> det(R) < 0, Rs)
    gname == "Cs" && return a[mirror] == 0 ? "Ap" : "App"
    gname == "C3v" && return a[mirror] == 0 ? "A1" : "A2"
    # C2v, C4v, C6v: A/B from the principal rotation, subscript from σ_v
    letter = a[_principal_rotation(Rs)] == 0 ? "A" : "B"
    σv = letter == "A" ? mirror : _sigma_v(Rs, ctx)
    return letter * (a[σv] == 0 ? "1" : "2")
end

# Mulliken name of a two-dimensional representation of a 2D point group
function _name_2d(gname::String, E::_Irrep2D, Rs::Vector{<:AbstractMatrix}) :: String
    gname == "C6v" || return "E"
    c2 = findfirst(R -> det(R) > 0 && abs(_angle2d(R) - π) < 1e-8, Rs)
    return real(E.character[c2]) < 0 ? "E1" : "E2"
end

# A sector of a little co-group: a one-dimensional representation `exponents` of the
# subgroup `elements` (indices into the little co-group). For a one-dimensional irrep
# the subgroup is the whole group; a two-dimensional irrep `parent` is represented by its
# two partners on the subgroup ker(det E), on which it splits into two 1D representations.
struct _PointGroupSector
    name::String
    parent::String
    dimension::Int
    elements::Vector{Int}
    exponents::Vector{Int}
end

# all sectors of a two-dimensional point group given by its elements in the lattice basis
# (and the names of skipped three-dimensional irreps, of which there are none in 2D)
function _pointgroup_sectors(Ws::Vector{Matrix{Int}}, lattice::Lattice, ctx::_NamingContext)
    G = _FiniteGroup(Ws)
    Ws = G.elements
    Rs = [lattice.A' * W / lattice.A' for W in Ws]
    gname = _pointgroup_name_2d(Rs)
    irreps1 = _irreps_1d(G)
    irreps2 = _irreps_2d(G, irreps1)
    n1, n2 = length(irreps1), length(irreps2)
    if n1 + 4 * n2 != length(G) || n1 + n2 != _nclasses(G)
        error("Incomplete set of irreducible representations for $gname. This is a bug, please report!")
    end

    sectors = _PointGroupSector[]
    for a in irreps1
        name = _name_1d(gname, a, Rs, ctx)
        push!(sectors, _PointGroupSector(name, name, 1, collect(1:length(G)), a))
    end
    for E in irreps2
        parent = _name_2d(gname, E, Rs)
        Hidx = [i for i in 1:length(G) if E.det[i] == 0]
        RH = Rs[Hidx]
        partners = 0
        for ρ in _irreps_1d(_FiniteGroup(Ws[Hidx]))
            multiplicity = sum(conj(_root(ρ[k])) * E.character[Hidx[k]] for k in eachindex(Hidx)) / length(Hidx)
            isapprox(multiplicity, 1; atol=1e-8) || continue
            name = _cn_name(length(Hidx), _cn_exponent(ρ, RH))
            startswith(name, parent) || error("Unexpected partner $name of $parent. This is a bug, please report!")
            push!(sectors, _PointGroupSector(name, parent, 2, Hidx, ρ))
            partners += 1
        end
        partners == 2 || error("Could not split the two-dimensional irrep $parent of $gname. This is a bug, please report!")
    end
    names = [s.name for s in sectors]
    allunique(names) || error("Ambiguous irrep names $names for $gname. This is a bug, please report!")
    return gname, Ws, sort(sectors; by=s -> s.name), String[]
end
