using Dates

@doc raw"""
    write_toml(flattice::FiniteLattice, opsum::OpSum, filename::String; zero_based::Bool=false, return_string::Bool=false)

Writes `OpSum` defined on a `FiniteLattice` into a TOML file
containing site coordinates and interactions.

The output format is:
```TOML
Coordinates = [
  [3.0, -3.0, 2.0],
  [2.0, -2.0, 0.0],
  ...
]

Interactions = [
  ['coupling_1', 'type_1', i_1, j_1],
  ['coupling_2', 'type_2', i_2, j_2],
  ...
]
```

Coordinates are obtained from `atoms(flattice)` as Vector{Euclidean} and
converted to `Vector{Float64}`, and rounded according to `flattice.tol`.

# Arguments
- `flattice::FiniteLattice`: FiniteLattice object containing the lattice;
- `opsum::OpSum`: OpSum object containing the operators;
- `filename::String`: Full path to the output TOML file.

# Keyword arguments
- `zero_based::Bool=false`: If true, site indices are 0-based instead of 1-based.
- `return_string::Bool=false`: If true, the function returns the TOML string instead of writing to file and ignores `filename`.
"""
function write_toml(flattice::FiniteLattice, opsum::OpSum, filename::String; zero_based::Bool=false, return_string::Bool=false)
    # write meta-data to TOML file
    out_str = toml_metadata()
    out_str *= "\n"

    # write lattice data to TOML file
    out_str = toml_lattice(flattice; out_str=out_str)
    out_str *= "\n"
    
    # get string for `Coordinates` section of TOML file
    out_str *= toml_coordinates(flattice)
    out_str *= "\n"

    # get string for `Interactions` section of TOML file
    out_str = toml_interactions(opsum; zero_based=zero_based, out_str=out_str)

    if return_string
        return out_str
    else
        open(filename, "w") do f
            write(f, out_str)
        end
    end
end

# get meta-data string
function toml_metadata() :: String
    date = Dates.today()
    latlib_version = get_latlib_version() # defined in utils.jl
    meta_str = "# This file was generated by Latlib.jl on " * string(date)
    meta_str *= " under version " * latlib_version * ".\n"
    return meta_str
end

# output lattice parameters
function toml_lattice(flattice; out_str::String="") :: String

    # determine rounding precision from tolerance
    digits = max(0, -floor(Int, log10(flattice.tol)))


    # lattice vectors
    out_str *= "# Lattice vectors: "
    for (i, v) in enumerate(lattice_vecs(flattice))
        rounded = [round(x; digits=digits) for x in v.coords]
        trailing = i < length(lattice_vecs(flattice)) ? ", " : ""
        out_str *= "a$i=(" * join(rounded, ", ") * ")" * trailing
    end
    out_str *= "\n"
    
    # atom positions (Cartesian basis)
    out_str *= "# Atom positions (Cartesian basis): "
    for (i, v) in enumerate(positions(flattice))
        rounded = [round(x; digits=digits) for x in to_euclidean_basis(v).coords]
        trailing = i < length(positions(flattice)) ? ", " : ""
        out_str *= "(" * join(rounded, ", ") * ")" * trailing
    end
    out_str *= "\n"

    # atom positions (lattice basis)
    out_str *= "# Atom positions (lattice basis): "
    for (i, v) in enumerate(positions(flattice))
        rounded = [round(x; digits=digits) for x in v.coords]
        trailing = i < length(positions(flattice)) ? ", " : ""
        out_str *= "(" * join(rounded, ", ") * ")" * trailing
    end
    out_str *= "\n"

    # torus vectors (Cartesian basis)
    out_str *= "# Torus vectors (Cartesian basis): "
    for (i, v) in enumerate(boundary(flattice))
        rounded = [round(x; digits=digits) for x in to_euclidean_basis(v).coords]
        trailing = i < length(boundary(flattice)) ? ", " : ""
        out_str *= "t$i=(" * join(rounded, ", ") * ")" * trailing
    end
    out_str *= "\n"

    # torus vectors (lattice basis)
    out_str *= "# Torus vectors (lattice basis): "
    for (i, v) in enumerate(boundary(flattice))
        rounded = [round(x; digits=digits) for x in v.coords] # TO-DO: rounding may be suboptimal here
        trailing = i < length(boundary(flattice)) ? ", " : ""
        out_str *= "t$i=(" * join(rounded, ", ") * ")" * trailing
    end
    out_str *= "\n"

    return out_str
end

# get `Coordinates` section for TOML file as string
function toml_coordinates(flattice::FiniteLattice; out_str::String="") :: String
    
    # determine rounding precision from tolerance
    digits = max(0, -floor(Int, log10(flattice.tol)))

    # get site coordinates as Vector{EuclideanVector}
    euc_coords = atoms(flattice)

    # write coordinates
    out_str *= "Coordinates = [\n"
    for (i, v) in enumerate(euc_coords)
        rounded = [round(x; digits=digits) for x in v.coords]
        trailing = ","
        out_str *= "  [" * join(rounded, ", ") * "]" * trailing * "\n"
    end
    out_str *= "]\n"
    return out_str
end


# get `Interactions` section for TOML file as string
function toml_interactions(opsum::OpSum; zero_based::Bool=false, out_str::String="") :: String
    
    # 0 or 1-based indexing?
    offset = zero_based ? 1 : 0 
    
    # write interactions
    out_str *= "Interactions = [\n"
    for (i, op) in enumerate(opsum.ops)
        s1 = op.sites[1] - offset
        s2 = op.sites[2] - offset
        trailing = ","
        out_str *= "  ['" * op.cpl * "', '" * op.type * "', " * string(s1) * ", " * string(s2) * "]" * trailing * "\n"
    end
    out_str *= "]\n"
    return out_str
end


